# Site settings
baseURL = "//www.icepicky.com/"
languageCode = "en-US"
title = "Jose Ibarra"
theme = "hugo-theme-console"
# Added for publishing on Github Pages
publishDir = "docs"

[[params.navLinks]]
  name = "resume/"
  url = "resume/"

[[params.navLinks]]
  name = "projects/"
  url = "projects/"

[[params.navLinks]]
  name = "blog/"
  url = "blog/"

[params]
  # Metadata for search engines and social sharing
  name = "Jose Ibarra"
  description = "Jose Ibarra is a staff software engineer at Bonusly and MCS and BS Computer Science graduate from Arizona State University. He previously worked at Gusto, General Motors, and Sandia National Labs."
  shareImage = "static/img/jose.jpg"
  # twitterHandle = "icepickpenguin"

  # Favicon
  favicon = "favicon.ico"

  # Copyright
  copyright = "2018-2025 Jose Ibarra"
